### PR TITLE
chore(deps): update

### PR DESCRIPTION
**Pull request by evilebottnawi**
BREAKING CHANGE: use `md4` by default for hashing

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Use `md4` by default for perf reasons

### Breaking Changes

Yes

### Additional Info

No

### CODE REVIEW

**Comment by jens-duttke** [comment]
May I ask why the default has been switched to MD4? Referring Wikipedia, the risk of a collision is much higher than for MD5 hashes.

I assume it can't be the speed on modern computers.

**Comment by evilebottnawi** [comment]
@jens-duttke for perf reasons, webpack also uses md4 for hashing

> risk of a collision

No, not in out cases

**Comment by mrlubos** [comment]
> @jens-duttke for perf reasons, webpack also uses md4 for hashing
> 
> > risk of a collision
> 
> No, not in out cases

Can you explain why please?

**Comment by krysopath** [comment]
when you retire a hash algo for security reasons, then it would be also a pretty valid reason to switch to sha256 algo or similar. I cant see the reason at all.

**Comment by odensc** [comment]
I'd assume what @evilebottnawi meant is that since the hash is used for caching purposes (not cryptographic purposes) it doesn't matter if there's a high collision risk, because the consequences in the event of a collision are close to nil.

However a non-cryptographic hash function such as xxHash would be much better suited to this use-case than an obsolete cryptographic hashing function, and would most likely be even faster.

It would be nice to get some insight into the reasoning behind this change from the maintainer themselves.

**Comment by evilebottnawi** [comment]
> I'd assume what @evilebottnawi meant is that since the hash is used for caching purposes (not cryptographic purposes)

Yes

> However a non-cryptographic hash function such as xxHash would be much better suited to this use-case than an obsolete cryptographic hashing function, and would most likely be even faster.

yes, but we can't use it because it is require library compilation and can incompatibility with some platforms  

Why `md4`?

- not cryptographic purposes
- integration `xxHash` can be problematic
- `md4` and `md5` has collisions 
- `md4` is faster than `md5`

So using `md4` is best solution right now

**Comment by tomaszs** [comment]
This change is marked as breaking change. How to adjust file-loader to comply with this change?

**Comment by digilist** [comment]
@tomaszs I do not know the intention of the library authors for sure, but I guess they chose to bump the major version, because the build result will be different and so all caches will be invalidated. So I think there is no change necessary and you can simply update (this is what I did).

**Pull request merged**
