### PR TITLE
docs(README): replaced Rule.loader with Rule.use in single loader examples

### LINKED ISSUE #314: Update documentation to reflect Webpack v4
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The doc for file-loader has referred to the style recommended by Webpack 3 in multiple places where instead of using `use`, and specify `loader` and `options` inside the `use` object, `loader` and `options` have been used directly inside rules.
screen shot 2018-12-26 at 11 58 59 pm

### Your Proposal for Changes
Just an example of how the above could possibly be changed: 
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]',
            },
          },
        ],
      },
    ],
  },
};
```

### PR DESCRIPTION
**Pull request by alanyinjs**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Ref: issue #314 

This PR aims to update the doc to reflect use of `Rule.loader` and `Rule.use` in the case of using single (rather than multiple) loaders. This being said, Webpack official docs only deprecated the use of `Rule.loaders` rather than `Rule.loader`. In particular, it pointed out that `Rule.loader` can be used as a shortcut to `Rule.use: [ { loader } ]` (as seen in the following screenshot):
screen shot 2018-12-27 at 10 08 43 pm

However most loaders have updated their docs to consistently use `Rule.use` rather than `Rule.loader` even in the case of using a single loader:
[https://webpack.js.org/loaders/babel-loader/](https://webpack.js.org/loaders/url-loader/)
[https://webpack.js.org/loaders/babel-loader/](https://webpack.js.org/loaders/url-loader/)

### Breaking Changes

No breaking changes

### Additional Info

N/A
fixes #314

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@alanyinjs Thanks for PR, need accept CLA

**Comment by evilebottnawi** [comment]
Also please use commit message not more 72 characters :+1:

**Comment by alanyinjs** [comment]
@evilebottnawi sorry for the delay. should be good to look at now 😄

**Comment by alanyinjs** [comment]
Not a problem at all :smile

**Comment by alanyinjs** [comment]
Not a problem at all :smile:

**Pull request merged**
