### PR TITLE
fix(schema): added description on esModule

### PR DESCRIPTION
**Pull request by smondal**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Added 'description' field on esModule option.

### CODE REVIEW

**Comment by anikethsaha** [comment]
CI is not passing
run `npm run test` locally

I guess is there some security alert, you need to do auditing of the dep

**Comment by smondal** [comment]
Yes, Its passing everything in locally. 
Screen Shot 2019-12-29 at 4 19 05 PM

**Comment by anikethsaha** [comment]
`npm audit` ?

**Comment by smondal** [comment]
There was a security issue on serialize-javascript, fixed this. thanks @anikethsaha

**Comment by anikethsaha** [comment]
cool 👍

**Pull request merged**
