### PR TITLE
feat: Emit files with relative urls

### LINKED ISSUE #62: Allow option for relative URLs
I have a scenario where I need the file-loader to return the url relative not absolute to the output path. Please allow an option to do this. Currently, I'm filtering out the pre-prended '/' with sed.

### PR DESCRIPTION
**Pull request by adriancmiranda**
**What kind of change does this PR introduce?**
A feat

**Did you add tests for your changes?**
The old tests should work.

**If relevant, did you update the README?**
The old docs should work too.

**Summary**

Emit files with relative urls
Fixes #62 and #46 

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by adriancmiranda** [comment]
@d3viant0ne I'm sorry for the sequence of 'commit'. I'll do it all soon. Thank´s!

**Comment by adriancmiranda** [comment]
Done!

**Comment by huan086** [comment]
Doesn't seem to handle my case

```js
module.exports = {
    entry: { "js/server": [ "./folder1/script1.jsx", "./folder2/script1.jsx" ] }
...
```

`./folder1/script1.jsx` has `require("../content/images/picture.png")` (relative to folder1)

The generated path is

`module.exports = __webpack_require__.p + "../content/images/content/images/picture.png";`

when I expected it to be

`module.exports = __webpack_require__.p + "../content/images/picture.png";` (relative to js)

**Comment by adriancmiranda** [comment]
You can't use the [path] no the name

**Comment by huan086** [comment]
@adriancmiranda nice catch!

There's another problem, which I don't know if it should be fixed by url-loader or file-loader or ExtractTextPlugin or webpack itself

My output folder is
```js
    output: {
        path: path.resolve(__dirname, ".")
```

In `./folder1/folder2/script1.jsx`, i have an `import "../../content/bootstrap.css";`

In `bootstrap.css`, it has
```css
@font-face {
  src: url('../fonts/glyphicons-halflings-regular.eot');
```
Folder structure
```
root
|-content
| |-bootstrap.css
| `-fonts
|   `-glyphicons-halflings-regular.eot
`-folder1
  `-folder2
    `-script1.jsx
```

It resulted in server.css
```css
src:url(../fonts/glyphicons-halflings-regular.eot)
```
which is invalid and `./fonts/glyphicons-halflings-regular.eot` being emitted

Expected output
Folder structure
```
root
|-content
| |-bootstrap.css
| `-fonts
|   `-glyphicons-halflings-regular.eot
|-folder1
| `-folder2
|   `-script1.jsx
`-js
  |-server.js
  `-server.css
```

I think for the issue 46 involving CSS, it can never be fixed as long as webpack don't handle CSS separately
https://github.com/webpack-contrib/file-loader/issues/46#issuecomment-196549110

**Comment by adriancmiranda** [comment]
I don't know if I understand the problem(Mainly without view the webpack.config), you mean something like this?
https://bitbucket.org/adriancmiranda/pr-file-loader/src

**Comment by huan086** [comment]
Wow! Close enough. In https://bitbucket.org/adriancmiranda/pr-file-loader/src/266ff6b5bd76b4f434cf21a61904f1198e36e1e5/content/bootstrap.css?at=master&fileviewer=file-view-default

change to `url("../fonts/bold-cyrillic-ext.woff2")` (double dots)

I'm thinking of using the following to fix
1. Change all URL in css to absolute path relative to root. e.g. `/content/fonts/bold-cyrillic-ext.woff2`
2. When it reaches `url-loader`, treat absolute path as relative to root, and modify the path to become relative to the javascript file containing the module.export. e.g. `<output directory>/server.js` would have `module.export = "@font-face { ... url(./content/fonts/bold-cyrillic-ext.woff2) ... }`
3. `file-loader` would emit files under `<output directory>/content/fonts/bold-cyrillic-ext.woff2`
4. ExtractTextPlugin, when configured to output the css to a directory other than `<output directory>/server.css`, would modify the `url` accordingly.

I'm new to webpack, no idea whether the above would work or not...

**Comment by adriancmiranda** [comment]
Ok, let me see:

If you put `../fonts` (with double dots), the require method can't resolve this path because doesn't exists fonts directory on the root directory, this will generate an error, anyway, if I put the `fonts` directory in the `root`, generates an `outputPath` correct, but with a unexpected `url` in this specific case (pointing to a directory in the root).

*expected:*
`fonts`

*obtained:*
`../fonts` (without any change because the issuer context is pointing to up in relation to the font)

I'll fix this also validating the webpack public path parameter, not only outputPath (As I already do). Something like `path.relative(context, outputPath)` should be work, I think I can see about this later.

About the other things i.e. PostCSS and absolute paths

It solve but isn't the proposed solution.

**Comment by adriancmiranda** [comment]
It works, but I have to find a way to write the tests yet.
https://bitbucket.org/adriancmiranda/pr-file-loader/src/27e9759b53f82c9e543b6749062f4acf84c2bbb5/loaders/file-loader.js?at=master&fileviewer=file-view-default#file-loader.js-59

**Comment by d3viant0ne** [comment]
@adriancmiranda - Do you have anything else needing to be updated here pre you last comment or is this good to go?

**Comment by adriancmiranda** [comment]
@d3viant0ne I prefer keep it simple for now, so, yes!

**Comment by d3viant0ne** [comment]
@bebraw @michael-ciniawsky - Anything else before we we land this feature?

**Comment by bebraw** [comment]
@d3viant0ne Nope. It's good to go.

**Comment by adriancmiranda** [comment]
@huan086 I updated the sample folder, may you test for me again, please?
https://bitbucket.org/adriancmiranda/pr-file-loader/src
That should be working for your case too.

**Comment by Jorybraun** [comment]
I am having the same issue, 
about the output paths in the parent folder.

**Comment by adriancmiranda** [comment]
@Jorybraun This was already been solved, follow it [here](#150), please 😉

**Pull request merged**
