### PR TITLE
Removed duplicate file .prettierrc 

### PR DESCRIPTION
**Pull request by smondal**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
  There are two prettier file, So removed the duplicate one.
### Breaking Changes
  No breaking changes. Just remove duplicate file

### CODE REVIEW

**Comment by anikethsaha** [comment]
@smondal you need to sign the CLA

**Comment by smondal** [comment]
@anikethsaha  can you please let me know how do I sign the CLA, because If i click on "CLA" link, its open a form but not "submit" option there.

**Comment by anikethsaha** [comment]
you need to sign in through GitHub and then fill the details and submit

**Comment by smondalwsgc** [comment]
@anikethsaha can you please send me the link from where I can sign in CLA. Because If I click "CLA" link its open "https://cla.js.foundation/webpack-contrib/file-loader?pullRequest=354" but no "submit" button showing.

**Comment by smondal** [comment]
@anikethsaha can you please send me the link from where I can sign in CLA. Because If I click "CLA" link its open "https://cla.js.foundation/webpack-contrib/file-loader?pullRequest=354" but no "submit" button showing.

**Comment by anikethsaha** [comment]
Did you sign in using github ?

image

**Comment by smondal** [comment]
Yes, After sign in below page is showing to me. There is no submit button. Also its showing me "You have sign the CLA"

Screen Shot 2019-12-29 at 2 01 14 PM


Screen Shot 2019-12-29 at 1 58 12 PM

**Comment by anikethsaha** [comment]
try closing this PR and reopening this one

**Comment by smondal** [comment]
Ok, I am closing this pull request and open another one

**Pull request closed without merging**
